services:
  redis:
    build:
      context: buildfiles
      dockerfile: redis.dockerfile
    env_file:
      - .env
    restart: on-failure
    ports:
      - "6380:6379"
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
        - POSTGRES_DB=kulsary_taxi_db
        - POSTGRES_USER=aslan
        - POSTGRES_PASSWORD=povt203
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5433:5432"
  bot:
    build:
      context: .
      dockerfile: buildfiles/Dockerfile
    env_file:
      - .env
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis


volumes:
  pgdata:
